# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-comments-server:
    labels:
      lsb2.template.description: "Comments Server for local environment"
      lsb2.version: "local"
    image: "jghamburg/lsb2-comments:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: ./build/libs/lsb2-comments.jar
    ports:
      - "9000:9000" # web port
      - "49000:49000" # debug port
    environment:
      PROFILE: "local"
      DEBUG_PORT: 49000
#      JAVA_REMOTE_DEBUGGING: "true"
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true
