# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-comments-server:
    labels:
      de.otto.template.description: "Comments Server for local environment"
      de.otto.drop.brandshopupdater.version: "local"
    image: "comments-server:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    ports:
      - "9000:9000" # web port
      - "49000:49000" # debug port
    environment:
      PROFILE: "local"
      JAVA_REMOTE_DEBUGGING: "true"
      DEBUG_PORT: 49000
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true
